title: Jan Faracik
author: Jan Faracik
description: Personal Website for Jan Faracik
twitter_username: janfaracik
github_username: janfaracik
linkedin_username: janfaracik

plugins:
    - jekyll-feed

markdown: kramdown

sass:
  style: compact
