title: Jan Faracik
author: Jan Faracik
description: Personal Website for Jan Faracik

plugins:
  - jekyll-feed

markdown: kramdown

sass:
  style: compact

collections:
  posts:
    output: true
  projects:
    output: true
